# Generated by Django 5.0.3 on 2024-03-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
    ]
