# Generated by Django 5.0.3 on 2024-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_aluno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='notas',
            field=models.ManyToManyField(blank=True, db_column='pk', related_name='+', to='analytics.prova'),
        ),
    ]
