# Generated by Django 5.0.3 on 2024-03-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_aluno_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='notas',
            field=models.ManyToManyField(blank=True, db_column='pk', related_name='prova', to='analytics.prova'),
        ),
    ]
